# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kasuariweb.com
email: railondi@kasuariweb.com
description: > # this means to ignore newlines until "baseurl:"
  Seorang Programmer Java, PHP. Sempat mempelajari SEO dan Hacking. Tertarik bereksperimen untuk menggabungkan kedua teknik ini.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kasuariweb.com" # the base hostname & protocol for your site
twitter_username: railondi
github_username:  kasuariweb

# Build settings
markdown: kramdown
